# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catchdeal', '0002_auto_20161201_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
