# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catchdeal', '0003_auto_20161201_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
